###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/9

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Test5",
    "surname": "Test5",
    "email": "test5@mail.com",
    "password": "1234",
    "phone": "987654312",
    "adress": "Fake st. 12345",
    "dni": "12345678Y",
    "gender": "other",
    "category": "encargado",
    "warehouse_id":"1"
}

###
PUT http://localhost:3000/api/users/11
Content-Type: application/json

{
    "name": "peticion PUT1",
    "surname": "peticion PUT1",
    "email": "testPUT1@mail.com",
    "password": "1234",
    "phone": "987654322",
    "adress": "Fake st. 12345",
    "dni": "12387645Y",
    "gender": "other",
    "category": "operario",
    "warehouse_id":"4"
}

###
DELETE  http://localhost:3000/api/users/8

###
GET http://localhost:3000/api/orders

###
GET http://localhost:3000/api/orders/4

###
GET http://localhost:3000/api/orders/user/10

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "addressee": "datos de prueba",
    "description":"prueba de busqwueda",
    "n_items": 7,
    "destination_address": "C/ Yordi 19",
    "departure_date": "1996-09-12",
    "arrival_date": "1996-09-23",
    "truck_plate":"0000AAY"
}

###
DELETE  http://localhost:3000/api/orders/2

###
PUT http://localhost:3000/api/orders/
Content-Type: application/json

{
    "addressee": "admin",
    "description":"C/ Yordi 18",
    "n_items": 5,
    "destination_address": "26",
    "departure_date": "1996-09-18",
    "arrival_date": "1996-09-18",
    "truck_plate":"7894PLQ"
}


###
PUT http://localhost:3000/api/orders/4/departureDate
Content-Type: application/json

{
    "departure_date":"1996-09-21"
}

###
PUT http://localhost:3000/api/orders/4/arrivalDate
Content-Type: application/json

{
    "arrival_date":"1997-09-20"
}

###
PUT http://localhost:3000/api/orders/4/category
Content-Type: application/json

{
    "category":"a"
}

###
PUT http://localhost:3000/api/orders/26/status
Content-Type: application/json

{
    "status":"1"
}

###
PUT http://localhost:3000/api/orders/15/warehouseId
Content-Type: application/json

{
    "warehouse_id":"7"
}


###
GET http://localhost:3000/api/warehouses

###
GET http://localhost:3000/api/warehouses/4

###
POST http://localhost:3000/api/warehouses
Content-Type: application/json

{
    "name": "Pere",
    "address":"C/ Yordi 18"  
}

###
PUT http://localhost:3000/api/warehouses/1
Content-Type: application/json

{
  "name": "Antonio",
  "address":"C/ Yordi 18"
}

###
DELETE  http://localhost:3000/api/warehouses/1

###
GET http://localhost:3000/api/orders/warehouse/2

###
GET http://localhost:3000/api/orders/warehouse/2/status/0

###
GET http://localhost:3000/api/orders/warehouse/2/status/1/category/e

###
GET http://localhost:3000/api/orders/addressee
Content-Type: application/json

{
  "addressee":"datos de prueba"
}

###
GET http://localhost:3000/api/warehouses/name
Content-Type: application/json

{
  "name": "almacen 3"
}

###
GET http://localhost:3000/api/users/dni
Content-Type: application/json

{
  "dni": "88888886Y"
}