###
GET http://localhost:3000/api/users


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Test1",
    "surname": "Test2",
    "email": "test1@mail.com",
    "password": "1234",
    "phone": "987654321",
    "adress": "Fake st. 1234",
    "dni": "88888886Y",
    "gender": "other",
    "category": "encargado"
}

###
PUT http://localhost:3000/api/users/4
Content-Type: application/json

{
    "name": "peticion PUT",
    "surname": "peticion PUT",
    "email": "test2@mail.com",
    "password": "12345",
    "phone": "987654322",
    "adress": "Fake st. 12345",
    "dni": "88888889Y",
    "gender": "other",
    "category": "operario"
}

###
DELETE  http://localhost:3000/api/users/8

###
GET http://localhost:3000/api/orders

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "addressee": "Pere",
    "description":"C/ Yordi 18",
    "n_items": 5,
    "destination_address": "26",
    "departure_date": "1996-09-18",
    "arrival_date": "1996-09-18",
    "truck_plate":"00000011Y"
}

###
DELETE  http://localhost:3000/api/orders/2

###
PUT http://localhost:3000/api/orders/
Content-Type: application/json

{
    "addressee": "admin",
    "description":"C/ Yordi 18",
    "n_items": 5,
    "destination_address": "26",
    "departure_date": "1996-09-18",
    "arrival_date": "1996-09-18",
    "truck_plate":"7894PLQ"
}


###
PUT http://localhost:3000/api/orders/4/departureDate
Content-Type: application/json

{
    "departure_date":"1996-09-21"
}

###
PUT http://localhost:3000/api/orders/4/arrivalDate
Content-Type: application/json

{
    "arrival_date":"1997-09-20"
}

###
PUT http://localhost:3000/api/orders/4/category
Content-Type: application/json

{
    "category":"a"
}

###
GET http://localhost:3000/api/warehouses

###
POST http://localhost:3000/api/warehouses
Content-Type: application/json

{
    "name": "Pere",
    "address":"C/ Yordi 18"  
}

###
PUT http://localhost:3000/api/warehouses/1
Content-Type: application/json

{
  "name": "Antonio",
  "address":"C/ Yordi 18"
}

###
DELETE  http://localhost:3000/api/warehouses/1

###
GET http://localhost:3000/api/orders/warehouse/2

###
GET http://localhost:3000/api/orders/warehouse/2/status/0

###
GET http://localhost:3000/api/orders/warehouse/2/status/1/category/e